FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /home/app

RUN apt-get update && \ 
   apt-get install -y libpq-dev gcc && \
   apt-get clean

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt --no-cache-dir

# COPY . .

# RUN chmod +x docker/dev/entrypoint.sh

# ENTRYPOINT [ "bash", "docker/dev/entrypoint.sh" ]

# CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload", "--log-level", "debug" ]