version: '3.9'

services:

  postgres:
    container_name: postgres
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - search-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    container_name: logstash
    build: 
      context: ./logstash/
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - CONFIG_SUPPORT_ESCAPE=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - postgres
    volumes:
      - logstash-data:/usr/share/logstash/data

  kibana:
    image: kibana:8.13.4
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  pgdata:
  search-data:
  logstash-data: 